version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_docker_image_1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkinsnet

  sonarqube:
    image: sonarqube
    container_name: sonarqube_docker_image_2
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - jenkinsnet

  artifactory:
    #image: docker.bintray.io/jfrog/artifactory-oss
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    container_name: artifactory_docker_image_3
    ports:
      - "8081:8081"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    networks:
      - jenkinsnet
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000  

volumes:
  jenkins_data:
  sonarqube_data:
  artifactory_data:

networks:
  jenkinsnet:
